In [1]:
import cv2 as cv
import numpy as np
from math import *
import os

Question-3

In [ ]:
loc = input("Enter your image location: ")
inter = int(input("Enter Interpolation factor: "))
# loc = r"C:\Users\sarth\Desktop\x5.bmp"
# inter = 4
img = cv.imread(loc,0)
cv.imshow('input image',img)
cv.waitKey(0)
print("Interpolation Factor is: ",inter)
def bilinear_interpolation(img,inter):
    a = np.array(img)
    S = a.shape
    # print(S)
    R = S[0]*inter
    C = S[1]*inter
    # print(type(R),type(C))
    mat = np.ones((R,C))*-1
    #Placing he values at their specific positions
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            mat[round(i*inter)][round(j*inter)] = a[i][j]
    #Range of known values
    x_mat = i*inter
    y_mat = j*inter
    # print(x_mat,y_mat)    
    for i in range(x_mat+1):  
        for j in range(y_mat+1):
            if mat[i][j] == -1:
                #Applying bilinear Interpolation for every NN in orignal Matrix
                x = i/inter
                y = j/inter

                if ceil(x) != x:
                    x1 = floor(x)
                    x2 = ceil(x)
                else: 
                    if x == 0:
                        x1 = 0
                        x2 = 1
                    else:
                        x1 = x-1
                        x2 = x
                if ceil(y) != y:
                    y1 = floor(y)
                    y2 = ceil(y)
                else: 
                    if y == 0:
                        y1 = 0
                        y2 = 1
                    else:
                        y1 = y-1
                        y2 = y
                #Neighbours co-ordinate ranges
                x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
                #X Matrix for Neighbours
                X = [
                    [x1,y1,x1*y1,1],[x1,y2,x1*y2,1],[x2,y2,x2*y2,1],[x2,y1,x2*y1,1]]
                V = [[a[x1][y1]],[a[x1][y2]],[a[x2][y2]],[a[x2][y1]]]
                # A = X^-1.V
                A = np.dot(np.linalg.inv(X),V)
                #Finding interpolated Pixel Value
                mat[i][j] = np.dot(np.array([x,y,x*y,1]),A)
    # Mirroring the Borders
    for i in range (x_mat+1):
        for j in range(y_mat+1,len(mat[0])):
            mat[i][j] = mat[i][j-1]

    for j in range(len(mat[0])):
        for i in range(x_mat+1,len(mat)):
            mat[i][j] = mat[i-1][j]
    return mat
mat_inter = bilinear_interpolation(img,inter)
print(mat_inter)
cv.imshow("Q3",np.uint8(mat_inter))
cv.waitKey(0)

Question - 4

In [2]:
rot = pi*45/180
scalex = 2
scaley = 2
transx = 30
transy = 30
loc2 = r'C:\Users\sarth\Desktop\assign1.jpg'
img2 = cv.imread(loc2,0)
a = np.array(img2)
# print(len(a))

whisper = 7*img2.shape[0]
R_2 = img2.shape[0]
C_2 = img2.shape[1]
cv.imshow("Input",np.uint8(img2))
cv.waitKey(0)

-1

In [6]:
print(R_2,C_2)
def transformation(rot,scalex,scaley,transx,transy):
    R = [
        [cos(rot),-sin(rot),0],
        [sin(rot),cos(rot),0],
        [0,0,1]
        ]
    R = np.array(R)
    S = [
        [scalex,0,0],
        [0,scaley,0],
        [0,0,1]
        ]
    S = np.array(S)
    T = [
        [1,0,0],
        [0,1,0],
        [transx,transy,1]
        ]
    T = np.array(T)
    T1 = np.matmul(R,S)
    Trans = np.matmul(T1,T)
    print("The Transformation Matrix is: ")
    print(Trans)
    return (Trans)
mat_T = transformation(rot,scalex,scaley,transx,transy)
mat_TI = np.linalg.inv(mat_T)
# print(img2.shape)
# print(np.linalg.inv(mat_T))
# V = np.empty((0,3),int)
# inver = 
# V = np.empty((img2.shape[0],img2.shape[1]))
def trans_interpolation(whisper,R_2,C_2,mat_TI,img2,a):
    at = np.ones((whisper,whisper))*-1
    for i in range(whisper):
        for j in range(whisper):
            # print(i,j)
            try:
                X1 = np.matmul(np.array([i-(2*R_2),j-(2*C_2),1]),mat_TI)
                # if ((X1[0][0]>=0) and (X1[0][0] <=R_2) and (X1[0][1]>=0) and (X1[0][1] <=C_2)):
                #Applying bilinear Interpolation for every NN in orignal Matrix
                x = X1[0]
                y = X1[1]
                # print(x,y)
                if(x<0 or x >= len(a) or y < 0 or y >= len(a[0])):
                    at[i][j] = 0
                    continue
                
                if ceil(x) != x:
                    x1 = floor(x)
                    x2 = ceil(x)
                else: 
                    if x == 0:
                        x1 = 0
                        x2 = 1
                    else:
                        x1 = x-1
                        x2 = x
                if ceil(y) != y:
                    y1 = floor(y)
                    y2 = ceil(y)
                else: 
                    if y == 0:
                        y1 = 0
                        y2 = 1
                    else:
                        y1 = y-1
                        y2 = y
                #Neighbours co-ordinate ranges
                x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
                #X Matrix for Neighbours
                X = [
                    [x1,y1,x1*y1,1],
                    [x1,y2,x1*y2,1],
                    [x2,y2,x2*y2,1],
                    [x2,y1,x2*y1,1]
                    ]
                V = [
                    [img2[x1][y1]],
                    [img2[x1][y2]],
                    [img2[x2][y2]],
                    [img2[x2][y1]]
                    ]
                # A = X^-1.V
                A = np.dot(np.linalg.inv(X),V)
                #Finding interpolated Pixel Value
                at[i][j] = np.dot(np.array([x,y,x*y,1]),A)
            except:
                at[i][j] = 0
    return at
# print(at)
mat1 = trans_interpolation(whisper,R_2,C_2,mat_TI,img2,a)
cv.line(mat1,(128,128),(128,400),(255,255,255),1)
cv.line(mat1,(128,128),(338,128),(255,255,255),1)
# cv.putText(at,"(0,0)",(38,128),cv.FONT_HERSHEY_SIMPLEX,1,(255,255,255),1)
cv.imshow("Output",np.uint8(mat1))
cv.waitKey(0)

64 64
The Transformation Matrix is: 
[[ 1.41421356 -1.41421356  0.        ]
 [ 1.41421356  1.41421356  0.        ]
 [30.         30.          1.        ]]
[[ 3.53553391e-01  3.53553391e-01  0.00000000e+00]
 [-3.53553391e-01  3.53553391e-01 -0.00000000e+00]
 [-1.66533454e-15 -2.12132034e+01  1.00000000e+00]]


-1

In [ ]:
os.chdir(r"C:\Users\sarth\Desktop")
cv.imwrite("Input.bmp",img2)
cv.imwrite("Output.jpg",mat1)

True

Question 5

In [8]:
#Using T = V-1X
# Using MS Paint to Manually find out the co-ordinates of the Matrix. The pixels co-ordinates were 
# (0,0) -> (158,158); (64,0) ->  (248,248); (64,64) -> (158,337) upto certain decimals. Keeping in 
# mind our padding (To account for the negative values, we kept a sufficiently large padding), 
# we can allot the following values to the co-ordinate.
O = cv.imshow("Unregistered Q4 Output",np.uint8(mat1))
I = cv.imshow("Input image Q4",img2)

cv.waitKey(0)
b = np.array(I)
# print(O[5][2],b[2])
VR = [
    [0,0,1],
    [64,0,1],
    [64,64,1]
    # [0,64,1]
    ]
XR =[
    [30,30,1],
    [120.51,-60.51,1],
    [211.02,30,1]
    # [69,247,1]
    ]
VRI = np.linalg.inv(VR)
Z = np.matmul(VRI,XR)

#Writing the code to register the matrix O, using Z inverse
ZI = np.linalg.inv(Z)
# print(ZI)
#Calling the function
Reg_O = trans_interpolation(whisper,R_2,C_2,ZI,img2,a)
cv.line(Reg_O,(128,128),(128,400),(255,255,255),1)
cv.line(Reg_O,(128,128),(338,128),(255,255,255),1)
# cv.putText(at,"(0,0)",(38,128),cv.FONT_HERSHEY_SIMPLEX,1,(255,255,255),1)
cv.imshow("Registered Image",np.uint8(Reg_O))
cv.waitKey(0)


[[ 3.53552094e-01  3.53552094e-01  0.00000000e+00]
 [-3.53552094e-01  3.53552094e-01 -0.00000000e+00]
 [ 1.66532232e-15 -2.12131256e+01  1.00000000e+00]]


-1